# Generated by Django 5.0.7 on 2024-08-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetestapi', '0004_alter_post_author_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
